workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script:
          npm install --save react-native@latest
      - name: pod init
        script:
          pod init
      - name: pods install
        script:
          pod install
      - name: ipa file
        script:
          npx react-native run-ios --configuration=Debug  
          