workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script:
          npm install --save react-native@latest
      - name: ipa file
        script:
          npx react-native run-ios --configuration=release  